worked on the post , getall and delete endpoint
hackercaleb/shortit-ts pull request #1
Opened 2024-04-05 18:54 UTC by hackercaleb

2024-04-06 13:09 UTC, greatertomi requested changes
A good start. But there could be more improvements
- When I try to use a custom name more than once, it throws a server error. It should return an error message that custom name is already used
- You need to add validation to the post route. When I send an empty object, it throws an error.

2024-04-06 13:09 UTC, greatertomi commented on src/controllers/shortener.controller.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Remove this eslint-disable

2024-04-06 13:09 UTC, greatertomi commented on src/controllers/shortener.controller.ts
Delete all the console.log in this file

2024-04-06 13:09 UTC, greatertomi commented on src/controllers/shortener.controller.ts
> +);
Extract this to a custom function and export it.

2024-04-06 13:09 UTC, greatertomi commented on .env
> +MONGO_URL = mongodb+srv://caleboshalusi:XQskTG1hGgs7VuGn@cluster0.dqdxx7i.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
Remove this .env file and create an .env.example file

2024-04-06 13:09 UTC, greatertomi commented on src/controllers/shortener.controller.ts
> +  const { originalUrl, customName } = req.body as CreateUrlBody;
- The requirement expects you to receive url

```suggestion
  const { url, customName } = req.body as CreateUrlBody;
```

2024-04-06 13:09 UTC, greatertomi commented on src/controllers/shortener.controller.ts
> +    const shortUrl = customName || nanoidGenerator();
> If the custom name has spaces, replace the spaces with dashes before adding it to the url. Save the custom name with spaces into the database.

Using the `customName` like this allows for the customName to have space

2024-04-06 13:09 UTC, greatertomi commented on src/controllers/shortener.controller.ts
> +    const getAllUrls = await ShortenedURL.find({});
```suggestion
    const getAllUrls = await ShortenedURL.find();
```

2024-04-06 13:09 UTC, greatertomi commented on src/controllers/shortener.controller.ts
> +      return res.status(200).json([]);
Extract all the HTTP_CODES in this PR to a constant file and use them from there

2024-04-06 13:09 UTC, greatertomi commented on src/controllers/shortener.controller.ts
> +    // to get all urls
This comment is not necessary
```suggestion
```

2024-04-06 13:09 UTC, greatertomi commented on src/routes/shortener.route.ts
> +//import { validate } from '../middleware/validate';
Delete this

2024-04-06 13:09 UTC, greatertomi commented on src/models/shortener.model.ts
> +  }
When fetching all the urls, you can improve the model by changing the `_id` to `id`. Remove the underscore. Also delete the __v

Something like this below should help.
<img width="578" alt="Screenshot 2024-04-06 at 13 33 24" src="https://github.com/hackercaleb/shortit-ts/assets/48496855/4f00ef13-2f98-45c4-b8e7-d82d0092d6b3">

2024-04-06 13:09 UTC, greatertomi commented on src/controllers/shortener.controller.ts
> +      data: null
When you delete a data, return the deleted data not `null`

2024-04-06 13:09 UTC, greatertomi commented on src/controllers/shortener.controller.ts
> +    }
```suggestion
    if (existingUrl) {
      return res.json({
        message: 'Original url already exists',
        data: { shortUrl: existingUrl.shortUrl }
      });
    
    }
```

2024-04-06 13:09 UTC, greatertomi commented on src/index.ts
> +};
Extract this database connection logic to a separate file

2024-04-09 20:10 UTC, greatertomi commented on src/controllers/shortener.controller.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Fixed on 73c307e

2024-04-10 20:11 UTC, hackercaleb commented
fixed on aea946a4e3e0e60e96df35aa5e2397e8cc24b0cf

2024-04-13 11:04 UTC, greatertomi approved these changes

2024-04-13 11:06 UTC, merged